### ISSUE TITLE
Just::concat() is broken

### ISSUE THREAD

**Issue by shadowhand** [php-fp/php-fp-maybe#4]
[This code is impossible](https://github.com/php-fp/php-fp-maybe/blob/773c2bc2f1f54030d53cba8d9a5fa1b391d06caf/src/Constructor/Just.php#L56-L60) because `Maybe` is an abstract class. Attempting to run it results in a fatal error.

**Comment by i-am-tom** [comment]
Huh - weird! How did the tests pass? O_o I'll sort this out. Thanks :)

**Comment by shadowhand** [comment]
If you look at the build for #3 you'll see that the code in question is not being tested.

**Comment by i-am-tom** [comment]
Oh dear! Thanks for noticing :)

**Comment by i-am-tom** [comment]
Sorted in the latest push :) I'll update packagist. Thanks again.
