### ISSUE TITLE
Maybe without value check?

### ISSUE THREAD

**Issue by shadowhand** [php-fp/php-fp-maybe#5]
Is `Maybe` missing a constructor that returns `Just` for a value, or `Nothing` for a null? From what I can tell, Haskell's `Maybe` constructor does a type check and returns a `Just` when given a value and `Nothing` otherwise. Would it make sense to have the following?

```php
$maybe = Maybe::of(null);
assert($maybe instanceof Nothing);

$maybe = Maybe::of(1);
assert($maybe instanceof Just);
```

Or, if the violates the Applicative constructor, perhaps the following?

```php
$maybe = Maybe::maybe(null); // Nothing
$maybe = Maybe::maybe(1); // Just
$maybe = Maybe::maybe(false); // Just
```

**Comment by i-am-tom** [comment]
I'd be happy to implement this as a function called something like `fromNullable`, but I'm hesitant to make it automatic. Haskell actually _doesn't_ do any `Maybe`-filling automatically, but the community has a much more well-ingrained sense of totality when it comes to writing functions. However, you can perfectly validly write:

```haskell
> :t Just ()
Just () :: Maybe ()
```

`()` is Unit, which is probably the closest value to "null" in Haskell.

**Comment by shadowhand** [comment]
I'm not too worried about it, something like this works perfectly well:

```php
return isset($value) ? Maybe::just($value) : Maybe::nothing();
```

**Comment by i-am-tom** [comment]
Yeah, agreed. I'll add it in, as I think it would help reinforce the idea that `Just(null)` _is_ valid but _really_ weird!
